"use client"

import { compact, currency } from "@/lib/analytics"
import { AnalyticsPage } from "@/components/analytics/analytics-page"
import {
  BarChartCard,
  DataTable,
  DonutActiveChartCard,
  HorizontalBarChartCard,
  RadialMetricCard,
  StatCard,
  StatGrid,
} from "@/components/analytics/analytics-widgets"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export default function ProductAnalyticsPage() {
  return (
    <AnalyticsPage
      title="Product Analytics"
      description="Analyze product performance, category revenue, popularity, and buyer reach."
    >
      {(analytics) => (
        <>
          <StatGrid>
            <StatCard label="Products" value={compact(analytics.overview.totalProducts)} detail="Unique product IDs" />
            <StatCard label="Units Sold" value={compact(analytics.overview.totalUnits)} detail="Total quantities" />
            <StatCard label="Category Count" value={String(analytics.productAnalytics.categoryRevenue.length)} detail="Revenue groups" />
            <StatCard label="Revenue" value={currency(analytics.overview.totalRevenue)} detail="Active dataset" />
          </StatGrid>

          <div className="grid gap-4 xl:grid-cols-2">
            <HorizontalBarChartCard
              title="Top Products"
              description="Products ranked by generated revenue."
              data={analytics.productAnalytics.productRevenue}
              valueFormatter={currency}
            />
            <BarChartCard
              title="Product Popularity"
              description="Quantity sold by product."
              data={analytics.productAnalytics.productPopularity}
            />
            <DonutActiveChartCard
              title="Category Revenue"
              description="Interactive revenue contribution by category."
              data={analytics.productAnalytics.categoryRevenue}
              valueFormatter={currency}
            />
            <HorizontalBarChartCard
              title="Product Revenue Analysis"
              description="Revenue generated by top products."
              data={analytics.productAnalytics.productRevenue}
              valueFormatter={currency}
            />
          </div>

          <div className="grid gap-4 xl:grid-cols-3">
            {analytics.productAnalytics.topProducts.slice(0, 3).map((product) => (
              <RadialMetricCard
                key={product.productId}
                title={product.productName}
                description={`${product.category} revenue contribution`}
                value={product.revenue}
                max={analytics.overview.totalRevenue}
                centerLabel={currency(product.revenue)}
              />
            ))}
          </div>

          <Card className="border-black/10 bg-white shadow-sm">
            <CardHeader>
              <CardTitle>Product List</CardTitle>
            </CardHeader>
            <CardContent>
              <DataTable
                columns={["Product", "Category", "Price", "Revenue", "Units", "Buyers"]}
                rows={analytics.productAnalytics.products.slice(0, 15).map((product) => [
                  product.productName,
                  product.category,
                  currency(product.price),
                  currency(product.revenue),
                  product.quantitySold,
                  product.buyers,
                ])}
              />
            </CardContent>
          </Card>
        </>
      )}
    </AnalyticsPage>
  )
}
